sudo: false
language: python
notifications:
  email:
    recipients:
      - willemjanfaber@fe2.nl
    on_success: change
    on_failure: always
python:
  - "2.7"
cache: apt
addons:
  apt:
    packages:
    - libdb-dev
    - libxml2-dev
    - libxslt1-dev
before_install:
  - bash install.sh
install:
  - pip install -r requirements.txt
script:
  - bash run-tests.sh
