sudo: yes
language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - willemjanfaber@fe2.nl
    on_success: change
    on_failure: always
cache: apt
addons:
  apt:
    packages:
    - libdb-dev
    - oracle-java8-installer
    - libxml2-dev
    - libxslt1-dev
    - pyton2.7
    - python-pip
    - virtualenv
install:
  - bash install.sh
script:
  - bash run-tests.sh
